name: CI-CD
on: [push, pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest -v

      - name: Check linting with black
        run: |
          black --check --diff flask_testing/

      - name: Check linting with isort
        run: |
          isort --check-only --diff --profile black flask_testing/

      - name: Check linting with flake8
        run: |
          flake8 flask_testing/

      - name: Check code type annotations with mypy
        run: |
          mypy flask_testing/
          
